// Generated by andromda-angular cartridge (view\view.component.imp.ts.vsl) CAN EDIT!
import { Component } from '@angular/core';
import { SearchLearningOutcomesComponent } from '@app/view/module/outcome/search-learning-outcomes.component';
import { SearchLearningOutcomesVarsForm } from '@app/view/module/outcome/search-learning-outcomes.component';
import { MatRadioChange } from '@angular/material/radio';
import { MatCheckboxChange } from '@angular/material/checkbox';
import { CommonModule } from '@angular/common';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { TranslateModule } from '@ngx-translate/core';
import { MaterialModule } from '@app/material.module';
import { CsvModule } from '@ctrl/ngx-csv';
import { TableComponent } from '@app/components/table/table.component';
import { LoaderComponent } from "@shared/loader/loader.component";
import { LearningOutcomeEditorImplComponent } from '@app/components/module/outcome/learning-outcome-editor-impl.component';

@Component({
  selector: 'app-search-learning-outcomes',
  templateUrl: './search-learning-outcomes.component.html',
  styleUrls: ['./search-learning-outcomes.component.scss'],
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    ReactiveFormsModule,
    TranslateModule,
    MaterialModule,
    CsvModule,
    TableComponent,
    LoaderComponent,
    LearningOutcomeEditorImplComponent,
  ],
})
export class SearchLearningOutcomesImplComponent extends SearchLearningOutcomesComponent {

    constructor() {
        super();
    }

    override beforeOnInit(form: SearchLearningOutcomesVarsForm): SearchLearningOutcomesVarsForm{     
        return form;
    }

    doNgOnDestroy(): void {
    }
}