// Generated by hibernate/SpringHibernateDaoImpl.vsl in andromda-spring-cartridge on $springUtils.date.
// license-header java merge-point
/**
 * This is only generated once! It will never be overwritten.
 * You can (and have to!) safely modify it by hand.
 */
package bw.co.roguesystems.thutego.programme;

import bw.co.roguesystems.thutego.curriculum.CurriculumRepository;
import org.springframework.stereotype.Repository;

/**
 * @see Programme
 */
@Repository("programmeDao")
public class ProgrammeDaoImpl
    extends ProgrammeDaoBase
{
    
    public ProgrammeDaoImpl(
        CurriculumRepository curriculumRepository,
        ProgrammeRepository programmeRepository
    ) {

        super(
            curriculumRepository,
            programmeRepository
        );
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public void toProgrammeVO(
        Programme source,
        ProgrammeVO target)
    {
        // TODO verify behavior of toProgrammeVO
        super.toProgrammeVO(source, target);
        // WARNING! No conversion for target.curricula (can't convert source.getCurricula():bw.co.roguesystems.thutego.curriculum.Curriculum to bw.co.roguesystems.thutego.curriculum.CurriculumVO
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProgrammeVO toProgrammeVO(final Programme entity)
    {
        // TODO verify behavior of toProgrammeVO
        return super.toProgrammeVO(entity);
    }

    /**
     * Retrieves the entity object that is associated with the specified value object
     * from the object store. If no such entity object exists in the object store,
     * a new, blank entity is created
     */
    private Programme loadProgrammeFromProgrammeVO(ProgrammeVO programmeVO)
    {
        // TODO implement loadProgrammeFromProgrammeVO
        throw new UnsupportedOperationException("bw.co.roguesystems.thutego.programme.loadProgrammeFromProgrammeVO(ProgrammeVO) not yet implemented.");

        /* A typical implementation looks like this:
        if (programmeVO.getId() == null)
        {
            return  Programme.Factory.newInstance();
        }
        else
        {
            return this.load(programmeVO.getId());
        }
        */
    }

    /**
     * {@inheritDoc}
     */
    public Programme programmeVOToEntity(ProgrammeVO programmeVO)
    {
        // TODO verify behavior of programmeVOToEntity
        Programme entity = this.loadProgrammeFromProgrammeVO(programmeVO);
        this.programmeVOToEntity(programmeVO, entity, true);
        return entity;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public void programmeVOToEntity(
        ProgrammeVO source,
        Programme target,
        boolean copyIfNull)
    {
        // TODO verify behavior of programmeVOToEntity
        super.programmeVOToEntity(source, target, copyIfNull);
    }
}