// Generated by andromda-angular cartridge (controller\controller.impl.ts.vsl) Can Modify
import { Injectable } from '@angular/core';
import { CurriculumController } from '@app/controller/curriculum/curriculum-controller';

@Injectable()
export class CurriculumControllerImpl extends CurriculumController {

    constructor() {
        super();
    }

}
