// Generated by andromda-angular cartridge (controller\controller.impl.ts.vsl) Can Modify
import { Injectable } from '@angular/core';
import { TopicController } from '@app/controller/module/topic/topic-controller';

@Injectable()
export class TopicControllerImpl extends TopicController {

    constructor() {
        super();
    }

}
