// Generated by hibernate/SpringHibernateDaoImpl.vsl in andromda-spring-cartridge on $springUtils.date.
// license-header java merge-point
/**
 * This is only generated once! It will never be overwritten.
 * You can (and have to!) safely modify it by hand.
 */
package bw.co.roguesystems.thutego.institution;

import org.springframework.stereotype.Repository;

/**
 * @see Institution
 */
@Repository("institutionDao")
public class InstitutionDaoImpl
    extends InstitutionDaoBase
{
    
    public InstitutionDaoImpl(
        InstitutionRepository institutionRepository
    ) {

        super(
            institutionRepository
        );
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public void toInstitutionVO(
        Institution source,
        InstitutionVO target)
    {
        // TODO verify behavior of toInstitutionVO
        super.toInstitutionVO(source, target);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InstitutionVO toInstitutionVO(final Institution entity)
    {
        // TODO verify behavior of toInstitutionVO
        return super.toInstitutionVO(entity);
    }

    /**
     * Retrieves the entity object that is associated with the specified value object
     * from the object store. If no such entity object exists in the object store,
     * a new, blank entity is created
     */
    private Institution loadInstitutionFromInstitutionVO(InstitutionVO institutionVO)
    {
        if (institutionVO.getId() == null)
        {
            return  Institution.Factory.newInstance();
        }
        else
        {
            return this.load(institutionVO.getId());
        }
    }

    /**
     * {@inheritDoc}
     */
    public Institution institutionVOToEntity(InstitutionVO institutionVO)
    {
        // TODO verify behavior of institutionVOToEntity
        Institution entity = this.loadInstitutionFromInstitutionVO(institutionVO);
        this.institutionVOToEntity(institutionVO, entity, true);
        return entity;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public void institutionVOToEntity(
        InstitutionVO source,
        Institution target,
        boolean copyIfNull)
    {
        // TODO verify behavior of institutionVOToEntity
        super.institutionVOToEntity(source, target, copyIfNull);
    }
}