// Generated by andromda-angular cartridge (service\service.impl.ts.vsl) CAN EDIT
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { CurriculumLevelVO } from '@app/model/bw/co/roguesystems/thutego/curriculum/level/curriculum-level-vo';
import { HttpClient } from '@angular/common/http';
import { Page } from '@app/model/page.model';
import { SearchObject } from '@app/model/search-object';

@Injectable({
  providedIn: 'root'
})
export class CurriculumLevelApi {

    protected path = '/curriculum/level';

    constructor(private http: HttpClient) {
    }

    public findById(id: number | any ): Observable<CurriculumLevelVO | any> {

        return this.http.get<CurriculumLevelVO | any>(this.path + `/${id}`);

    }

    public getAll(): Observable<CurriculumLevelVO[] | any[]> {

        return this.http.get<CurriculumLevelVO[] | any[]>(this.path);

    }

    public remove(id: number | any ): Observable<boolean | any> {

        return this.http.delete<boolean | any>(this.path + `/${id}`);

    }

    public save(curriculumLevel: CurriculumLevelVO | any ): Observable<CurriculumLevelVO | any> {

        return this.http.post<CurriculumLevelVO | any>(this.path, curriculumLevel);

    }

    public search(criteria: string | any ): Observable<CurriculumLevelVO[] | any[]> {

        return this.http.get<CurriculumLevelVO[] | any[]>(this.path + `/search?criteria=${criteria}`);

    }

}
