server:
    port: 8085
spring:
    thymeleaf:
        cache: false
    mvc:
        format:
            date: iso
            date-time: iso
            time: HH:mm:ss
        pathmatch:
            matching-strategy: ANT_PATH_MATCHER