// Generated by andromda-angular cartridge (view\components\component.ts.vsl) DO NOT EDIT
import {
  AfterViewInit,
  Component,
  effect,
  inject,
  Input,
  OnDestroy,
  OnInit,
  ViewChild,
} from "@angular/core";
import {COMMA, ENTER} from '@angular/cdk/keycodes';
import {
  FormsModule,
  ReactiveFormsModule,
  FormGroup,
  FormControl,
  FormBuilder,
  Validators,
  FormArray,
} from "@angular/forms";
import { SelectItem } from "@app/utils/select-item";
import { MatSelectChange } from '@angular/material/select';
import { MatRadioChange } from '@angular/material/radio';
import { MatCheckboxChange } from '@angular/material/checkbox';
import { MatChip, MatChipInput, MatChipInputEvent } from "@angular/material/chips";
import {MatAutocompleteSelectedEvent, MatAutocompleteModule} from '@angular/material/autocomplete';
import { MatDialog } from '@angular/material/dialog';
import { firstValueFrom, Observable, map, of, startWith } from "rxjs";
import { CommonModule } from '@angular/common';
import { TranslateModule } from '@ngx-translate/core';
import { MaterialModule } from '@app/material.module';
import { CsvModule } from '@ctrl/ngx-csv';
import { AccessPointTypeDTO } from '@app/model/bw/co/roguesystems/thutego/access/type/access-point-type-dto';
import { SearchObject } from '@app/model/search-object';
import { AccessPointEditorComponent } from './access-point-editor.component';
import { TableComponent } from '@app/components/table/table.component';
import { AccessPointTypeApiStore } from "@app/store/bw/co/roguesystems/thutego/access/type/access-point-type-api.store";
import { AccessPointApiStore } from "@app/store/bw/co/roguesystems/thutego/access/access-point-api.store";

@Component({
  selector: "app-access-point-editor",
  templateUrl: "./access-point-editor.component.html",
  styleUrls: [],
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    ReactiveFormsModule,
    TranslateModule,
    MaterialModule,
    CsvModule,
    TableComponent,
  ]
})
export class AccessPointEditorImplComponent extends AccessPointEditorComponent {

  readonly accessPointTypeStore = inject(AccessPointTypeApiStore);
  readonly accessPointApiStore = inject(AccessPointApiStore);
  private accessPointTypes$ = this.accessPointTypeStore.dataList;

  loadingTypes = false;

  constructor() {
    super();
    effect(() => {
      this.accessPointTypeBackingList = this.accessPointTypes$();
      if (this.loadingTypes) {
        this.loadingTypes = false;
        this.accessPointTypeFilteredList$ = of(this.accessPointTypeBackingList);
      }

      const accessPoint = this.accessPointApiStore.data();

      if (accessPoint) {
        this.accessPointTypeFilteredList$ = of([accessPoint.accessPointType]);

        setTimeout(() => {
          this.formGroupControl.patchValue(accessPoint);
          console.log('FormGroup updated:', this.formGroupControl);
        }, 0);
      }
    });
  }

  override filterAccessPointType() {
    this.loadingTypes = true;
    this.accessPointTypeStore.search({ criteria: this.accessPointTypeFilterCtrl.value });
  }

  override accessPointTypeCompare(o1: AccessPointTypeDTO | any, o2: AccessPointTypeDTO | any) {
    return o1 && o2 ? o1.id === o2.id : false;
  }

}
