// Generated by andromda-angular cartridge (view\view.component.imp.ts.vsl) CAN EDIT!
import { Component } from '@angular/core';
import { EditExitLevelOutcomeComponent } from '@app/view/curriculum/outcome/edit-exit-level-outcome.component';
import { EditExitLevelOutcomeVarsForm } from '@app/view/curriculum/outcome/edit-exit-level-outcome.component';
import { MatRadioChange } from '@angular/material/radio';
import { MatCheckboxChange } from '@angular/material/checkbox';
import { CommonModule } from '@angular/common';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { TranslateModule } from '@ngx-translate/core';
import { MaterialModule } from '@app/material.module';
import { CsvModule } from '@ctrl/ngx-csv';
import { TableComponent } from '@app/components/table/table.component';
import { LoaderComponent } from "@shared/loader/loader.component";
import { ExitLevelOutcomeDetailsImplComponent } from '@app/components/curriculum/outcome/exit-level-outcome-details-impl.component';
import { ExitLevelOutcomeEditorImplComponent } from '@app/components/curriculum/outcome/exit-level-outcome-editor-impl.component';

@Component({
  selector: 'app-edit-exit-level-outcome',
  templateUrl: './edit-exit-level-outcome.component.html',
  styleUrls: ['./edit-exit-level-outcome.component.scss'],
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    ReactiveFormsModule,
    TranslateModule,
    MaterialModule,
    CsvModule,
    TableComponent,
    LoaderComponent,
    ExitLevelOutcomeDetailsImplComponent,
    ExitLevelOutcomeEditorImplComponent,
  ],
})
export class EditExitLevelOutcomeImplComponent extends EditExitLevelOutcomeComponent {

    constructor() {
        super();
    }

    override beforeOnInit(form: EditExitLevelOutcomeVarsForm): EditExitLevelOutcomeVarsForm{     
        return form;
    }

    doNgOnDestroy(): void {
    }
}