// Generated by andromda-angular cartridge (view\view.component.imp.ts.vsl) CAN EDIT!
import { Component } from '@angular/core';
import { EditCurriculumOutcomeLevelComponent } from '@app/view/curriculum/outcome/edit-curriculum-outcome-level.component';
import { EditCurriculumOutcomeLevelVarsForm } from '@app/view/curriculum/outcome/edit-curriculum-outcome-level.component';
import { MatRadioChange } from '@angular/material/radio';
import { MatCheckboxChange } from '@angular/material/checkbox';
import { CommonModule } from '@angular/common';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { TranslateModule } from '@ngx-translate/core';
import { SharedModule } from '@app/@shared';
import { MaterialModule } from '@app/material.module';
import { CsvModule } from '@ctrl/ngx-csv';
import { TableComponent } from '@app/components/table/table.component';
import { ExitLevelOutcomeDetailsComponent } from '@app/components/curriculum/outcome/exit-level-outcome-details.component';
import { ExitLevelOutcomeEditorComponent } from '@app/components/curriculum/outcome/exit-level-outcome-editor.component';

@Component({
  selector: 'app-edit-curriculum-outcome-level',
  templateUrl: './edit-curriculum-outcome-level.component.html',
  styleUrls: ['./edit-curriculum-outcome-level.component.scss'],
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    ReactiveFormsModule,
    TranslateModule,
    SharedModule,
    MaterialModule,
    CsvModule,
    TableComponent,
    ExitLevelOutcomeDetailsComponent,
    ExitLevelOutcomeEditorComponent,
  ],
})
export class EditCurriculumOutcomeLevelImplComponent extends EditCurriculumOutcomeLevelComponent {

    constructor() {
        super();
    }

    override beforeOnInit(form: EditCurriculumOutcomeLevelVarsForm): EditCurriculumOutcomeLevelVarsForm{     
        return form;
    }

    doNgOnDestroy(): void {
    }
}