// Generated by andromda-angular cartridge (view\view.component.imp.ts.vsl) CAN EDIT!
import { Component } from '@angular/core';
import { ExitLevelOutcomeViewComponent } from '@app/view/curriculum/outcome/exit-level-outcome-view.component';
import { ExitLevelOutcomeViewVarsForm } from '@app/view/curriculum/outcome/exit-level-outcome-view.component';
import { MatRadioChange } from '@angular/material/radio';
import { MatCheckboxChange } from '@angular/material/checkbox';
import { CommonModule } from '@angular/common';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { TranslateModule } from '@ngx-translate/core';
import { MaterialModule } from '@app/material.module';

import { TableComponent } from '@app/components/table/table.component';
import { LoaderComponent } from "@shared/loader/loader.component";
import { ExitLevelOutcomeDetailsImplComponent } from '@app/components/curriculum/outcome/exit-level-outcome-details-impl.component';
import { ExitLevelOutcomeEditorImplComponent } from '@app/components/curriculum/outcome/exit-level-outcome-editor-impl.component';

@Component({
  selector: 'app-exit-level-outcome-view',
  templateUrl: './exit-level-outcome-view.component.html',
  styleUrls: ['./exit-level-outcome-view.component.scss'],
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    ReactiveFormsModule,
    TranslateModule,
    MaterialModule,

    TableComponent,
    LoaderComponent,
    ExitLevelOutcomeDetailsImplComponent,
    ExitLevelOutcomeEditorImplComponent,
  ],
})
export class ExitLevelOutcomeViewImplComponent extends ExitLevelOutcomeViewComponent {

    constructor() {
        super();
    }

    override beforeOnInit(form: ExitLevelOutcomeViewVarsForm): ExitLevelOutcomeViewVarsForm{
        return form;
    }

    doNgOnDestroy(): void {
    }
}
