// Generated by andromda-angular cartridge (view\view.component.imp.ts.vsl) CAN EDIT!
import { Component } from '@angular/core';
import { SearchCurriculumOutcomeLevelsComponent } from '@app/view/curriculum/outcome/search-curriculum-outcome-levels.component';
import { SearchCurriculumOutcomeLevelsVarsForm } from '@app/view/curriculum/outcome/search-curriculum-outcome-levels.component';
import { MatRadioChange } from '@angular/material/radio';
import { MatCheckboxChange } from '@angular/material/checkbox';
import { CommonModule } from '@angular/common';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { TranslateModule } from '@ngx-translate/core';
import { SharedModule } from '@app/@shared';
import { MaterialModule } from '@app/material.module';
import { CsvModule } from '@ctrl/ngx-csv';
import { TableComponent } from '@app/components/table/table.component';
import { ExitLevelOutcomeEditorImplComponent } from '@app/components/curriculum/outcome/exit-level-outcome-editor-impl.component';

@Component({
  selector: 'app-search-curriculum-outcome-levels',
  templateUrl: './search-curriculum-outcome-levels.component.html',
  styleUrls: ['./search-curriculum-outcome-levels.component.scss'],
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    ReactiveFormsModule,
    TranslateModule,
    SharedModule,
    MaterialModule,
    CsvModule,
    TableComponent,
    ExitLevelOutcomeEditorImplComponent,
  ],
})
export class SearchCurriculumOutcomeLevelsImplComponent extends SearchCurriculumOutcomeLevelsComponent {

    constructor() {
        super();
        this.success = this.exitLevelOutcomeApiStore.success;
        this.loading = this.exitLevelOutcomeApiStore.loading;
        this.error = this.exitLevelOutcomeApiStore.error;
        this.messages = this.exitLevelOutcomeApiStore.messages;
    }

    override beforeOnInit(form: SearchCurriculumOutcomeLevelsVarsForm): SearchCurriculumOutcomeLevelsVarsForm{
        return form;
    }

    doNgOnDestroy(): void {
    }
}
