// Generated by andromda-angular cartridge (view\view.component.imp.ts.vsl) CAN EDIT!
import { Component } from '@angular/core';
import { SearchExitLevelOutcomesComponent } from '@app/view/curriculum/outcome/search-exit-level-outcomes.component';
import { SearchExitLevelOutcomesVarsForm } from '@app/view/curriculum/outcome/search-exit-level-outcomes.component';
import { MatRadioChange } from '@angular/material/radio';
import { MatCheckboxChange } from '@angular/material/checkbox';
import { CommonModule } from '@angular/common';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { TranslateModule } from '@ngx-translate/core';
import { MaterialModule } from '@app/material.module';

import { TableComponent } from '@app/components/table/table.component';
import { LoaderComponent } from "@shared/loader/loader.component";
import { ExitLevelOutcomeEditorImplComponent } from '@app/components/curriculum/outcome/exit-level-outcome-editor-impl.component';

@Component({
  selector: 'app-search-exit-level-outcomes',
  templateUrl: './search-exit-level-outcomes.component.html',
  styleUrls: ['./search-exit-level-outcomes.component.scss'],
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    ReactiveFormsModule,
    TranslateModule,
    MaterialModule,

    TableComponent,
    LoaderComponent,
    ExitLevelOutcomeEditorImplComponent,
  ],
})
export class SearchExitLevelOutcomesImplComponent extends SearchExitLevelOutcomesComponent {

    constructor() {
        super();
    }

    override beforeOnInit(form: SearchExitLevelOutcomesVarsForm): SearchExitLevelOutcomesVarsForm{
        return form;
    }

    doNgOnDestroy(): void {
    }
}
