// Generated by andromda-angular cartridge (view\view.component.imp.ts.vsl) CAN EDIT!
import { Component } from '@angular/core';
import { EditCurriculumComponent } from '@app/view/curriculum/edit-curriculum.component';
import { EditCurriculumVarsForm } from '@app/view/curriculum/edit-curriculum.component';
import { MatRadioChange } from '@angular/material/radio';
import { MatCheckboxChange } from '@angular/material/checkbox';
import { CommonModule } from '@angular/common';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { TranslateModule } from '@ngx-translate/core';
import { MaterialModule } from '@app/material.module';

import { TableComponent } from '@app/components/table/table.component';
import { LoaderComponent } from "@shared/loader/loader.component";
import { CurriculumEditorImplComponent } from '@app/components/curriculum/curriculum-editor-impl.component';
import { CurriculumDetailsImplComponent } from '@app/components/curriculum/curriculum-details-impl.component';

@Component({
  selector: 'app-edit-curriculum',
  templateUrl: './edit-curriculum.component.html',
  styleUrls: ['./edit-curriculum.component.scss'],
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    ReactiveFormsModule,
    TranslateModule,
    MaterialModule,

    TableComponent,
    LoaderComponent,
    CurriculumEditorImplComponent,
    CurriculumDetailsImplComponent,
  ],
})
export class EditCurriculumImplComponent extends EditCurriculumComponent {

    constructor() {
        super();
        this.curriculumApiStore.reset();
        this.success = this.curriculumApiStore.success;
        this.loading = this.curriculumApiStore.loading;
        this.error = this.curriculumApiStore.error;
        this.messages = this.curriculumApiStore.messages;
    }

    override beforeOnInit(form: EditCurriculumVarsForm): EditCurriculumVarsForm{
        return form;
    }

    doNgOnDestroy(): void {
    }
}
