// Generated by andromda-angular cartridge (view\view.component.imp.ts.vsl) CAN EDIT!
import { Component } from '@angular/core';
import { SearchCurriculumComponent } from '@app/view/curriculum/search-curriculum.component';
import { SearchCurriculumVarsForm } from '@app/view/curriculum/search-curriculum.component';
import { MatRadioChange } from '@angular/material/radio';
import { MatCheckboxChange } from '@angular/material/checkbox';
import { CommonModule } from '@angular/common';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { TranslateModule } from '@ngx-translate/core';
import { SharedModule } from '@app/@shared';
import { MaterialModule } from '@app/material.module';
import { CsvModule } from '@ctrl/ngx-csv';
import { TableComponent } from '@app/components/table/table.component';
import { CurriculumDetailsComponent } from '@app/components/curriculum/curriculum-details.component';
import { CurriculumEditorComponent } from '@app/components/curriculum/curriculum-editor.component';
import { CurriculumSearchComponent } from '@app/components/curriculum/curriculum-search.component';

@Component({
  selector: 'app-search-curriculum',
  templateUrl: './search-curriculum.component.html',
  styleUrls: ['./search-curriculum.component.scss'],
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    ReactiveFormsModule,
    TranslateModule,
    SharedModule,
    MaterialModule,
    CsvModule,
    TableComponent,
    CurriculumDetailsComponent,
    CurriculumEditorComponent,
    CurriculumSearchComponent,
  ],
})
export class SearchCurriculumImplComponent extends SearchCurriculumComponent {

    constructor() {
        super();
    }

    override beforeOnInit(form: SearchCurriculumVarsForm): SearchCurriculumVarsForm{     
        return form;
    }

    doNgOnDestroy(): void {
    }
}