// Generated by andromda-angular cartridge (controller\controller.impl.ts.vsl) Can Modify
import { Injectable } from '@angular/core';
import { LearningFieldController } from '@app/controller/curriculum/field/learning-field-controller';

@Injectable()
export class LearningFieldControllerImpl extends LearningFieldController {

    constructor() {
        super();
    }

}
