// Generated by andromda-angular cartridge (view\view.component.imp.ts.vsl) CAN EDIT!
import { Component } from '@angular/core';
import { CurriculumLevelViewComponent } from '@app/view/curriculum/level/curriculum-level-view.component';
import { CurriculumLevelViewVarsForm } from '@app/view/curriculum/level/curriculum-level-view.component';
import { MatRadioChange } from '@angular/material/radio';
import { MatCheckboxChange } from '@angular/material/checkbox';
import { CommonModule } from '@angular/common';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { TranslateModule } from '@ngx-translate/core';
import { SharedModule } from '@app/@shared';
import { MaterialModule } from '@app/material.module';
import { CsvModule } from '@ctrl/ngx-csv';
import { TableComponent } from '@app/components/table/table.component';
import { CurriculumLevelEditorImplComponent } from '@app/components/curriculum/level/curriculum-level-editor-impl.component';
import { CurriculumLevelDetailsImplComponent } from '@app/components/curriculum/level/curriculum-level-details-impl.component';

@Component({
  selector: 'app-curriculum-level-view',
  templateUrl: './curriculum-level-view.component.html',
  styleUrls: ['./curriculum-level-view.component.scss'],
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    ReactiveFormsModule,
    TranslateModule,
    SharedModule,
    MaterialModule,
    CsvModule,
    TableComponent,
    CurriculumLevelEditorImplComponent,
    CurriculumLevelDetailsImplComponent,
  ],
})
export class CurriculumLevelViewImplComponent extends CurriculumLevelViewComponent {

    constructor() {
        super();
        this.success = this.curriculumLevelApiStore.success;
        this.loading = this.curriculumLevelApiStore.loading;
        this.error = this.curriculumLevelApiStore.error;
        this.messages = this.curriculumLevelApiStore.messages;
    }

    override beforeOnInit(form: CurriculumLevelViewVarsForm): CurriculumLevelViewVarsForm{
        return form;
    }

    doNgOnDestroy(): void {
    }
}
