// Generated by andromda-angular cartridge (view\view.component.imp.ts.vsl) CAN EDIT!
import { Component } from '@angular/core';
import { SearchCurriculumLevelsComponent } from '@app/view/curriculum/level/search-curriculum-levels.component';
import { SearchCurriculumLevelsVarsForm } from '@app/view/curriculum/level/search-curriculum-levels.component';
import { MatRadioChange } from '@angular/material/radio';
import { MatCheckboxChange } from '@angular/material/checkbox';
import { CommonModule } from '@angular/common';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { TranslateModule } from '@ngx-translate/core';
import { MaterialModule } from '@app/material.module';

import { TableComponent } from '@app/components/table/table.component';
import { LoaderComponent } from "@shared/loader/loader.component";
import { CurriculumLevelEditorImplComponent } from '@app/components/curriculum/level/curriculum-level-editor-impl.component';

@Component({
  selector: 'app-search-curriculum-levels',
  templateUrl: './search-curriculum-levels.component.html',
  styleUrls: ['./search-curriculum-levels.component.scss'],
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    ReactiveFormsModule,
    TranslateModule,
    MaterialModule,

    TableComponent,
    LoaderComponent,
    CurriculumLevelEditorImplComponent,
  ],
})
export class SearchCurriculumLevelsImplComponent extends SearchCurriculumLevelsComponent {

    constructor() {
        super();
    }

    override beforeOnInit(form: SearchCurriculumLevelsVarsForm): SearchCurriculumLevelsVarsForm{
        return form;
    }

    doNgOnDestroy(): void {
    }
}
