// Generated by andromda-angular cartridge (controller\controller.impl.ts.vsl) Can Modify
import { Injectable } from '@angular/core';
import { LeaningOutcomeController } from '@app/controller/module/outcome/leaning-outcome-controller';

@Injectable()
export class LeaningOutcomeControllerImpl extends LeaningOutcomeController {

    constructor() {
        super();
    }

}
