// Generated by andromda-angular cartridge (view\view.component.imp.ts.vsl) CAN EDIT!
import { Component } from '@angular/core';
import { EditLearningFieldComponent } from '@app/view/curriculum/field/edit-learning-field.component';
import { EditLearningFieldVarsForm } from '@app/view/curriculum/field/edit-learning-field.component';
import { MatRadioChange } from '@angular/material/radio';
import { MatCheckboxChange } from '@angular/material/checkbox';
import { CommonModule } from '@angular/common';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { TranslateModule } from '@ngx-translate/core';
import { SharedModule } from '@app/@shared';
import { MaterialModule } from '@app/material.module';
import { CsvModule } from '@ctrl/ngx-csv';
import { TableComponent } from '@app/components/table/table.component';
import { LearningFieldEditorImplComponent } from '@app/components/curriculum/field/learning-field-editor-impl.component';
import { LearningFieldDetailsImplComponent } from '@app/components/curriculum/field/learning-field-details-impl.component';

@Component({
  selector: 'app-edit-learning-field',
  templateUrl: './edit-learning-field.component.html',
  styleUrls: ['./edit-learning-field.component.scss'],
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    ReactiveFormsModule,
    TranslateModule,
    SharedModule,
    MaterialModule,
    CsvModule,
    TableComponent,
    LearningFieldEditorImplComponent,
    LearningFieldDetailsImplComponent,
  ],
})
export class EditLearningFieldImplComponent extends EditLearningFieldComponent {

    constructor() {
        super();
        this.success = this.learningFieldApiStore.success;
        this.loading = this.learningFieldApiStore.loading;
        this.error = this.learningFieldApiStore.error;
        this.messages = this.learningFieldApiStore.messages;
    }

    override beforeOnInit(form: EditLearningFieldVarsForm): EditLearningFieldVarsForm{
        return form;
    }

    doNgOnDestroy(): void {
    }

    override beforeEditLearningFieldSave(form: any): void {
      form.learningField = { ...this.learningFieldEditor?.learningFieldEditorForm?.value };
      console.log(form);
      this.learningFieldApiStore.save({
          field: form.learningField,
      });
  }
}
