// Generated by andromda-angular cartridge (view\view.component.imp.ts.vsl) CAN EDIT!
import { Component } from '@angular/core';
import { LearningFieldViewComponent } from '@app/view/curriculum/field/learning-field-view.component';
import { LearningFieldViewVarsForm } from '@app/view/curriculum/field/learning-field-view.component';
import { MatRadioChange } from '@angular/material/radio';
import { MatCheckboxChange } from '@angular/material/checkbox';
import { CommonModule } from '@angular/common';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { TranslateModule } from '@ngx-translate/core';
import { MaterialModule } from '@app/material.module';
import { CsvModule } from '@ctrl/ngx-csv';
import { TableComponent } from '@app/components/table/table.component';
import { LoaderComponent } from "@shared/loader/loader.component";
import { LearningFieldEditorImplComponent } from '@app/components/curriculum/field/learning-field-editor-impl.component';
import { LearningFieldDetailsImplComponent } from '@app/components/curriculum/field/learning-field-details-impl.component';

@Component({
  selector: 'app-learning-field-view',
  templateUrl: './learning-field-view.component.html',
  styleUrls: ['./learning-field-view.component.scss'],
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    ReactiveFormsModule,
    TranslateModule,
    MaterialModule,
    CsvModule,
    TableComponent,
    LoaderComponent,
    LearningFieldEditorImplComponent,
    LearningFieldDetailsImplComponent,
  ],
})
export class LearningFieldViewImplComponent extends LearningFieldViewComponent {

    constructor() {
        super();
    }

    override beforeOnInit(form: LearningFieldViewVarsForm): LearningFieldViewVarsForm{     
        return form;
    }

    doNgOnDestroy(): void {
    }
}