// Generated by andromda-angular cartridge (view\view.component.imp.ts.vsl) CAN EDIT!
import { Component } from '@angular/core';
import { SearchLearningFieldsComponent } from '@app/view/curriculum/field/search-learning-fields.component';
import { SearchLearningFieldsVarsForm } from '@app/view/curriculum/field/search-learning-fields.component';
import { MatRadioChange } from '@angular/material/radio';
import { MatCheckboxChange } from '@angular/material/checkbox';
import { CommonModule } from '@angular/common';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { TranslateModule } from '@ngx-translate/core';
import { MaterialModule } from '@app/material.module';

import { TableComponent } from '@app/components/table/table.component';
import { LoaderComponent } from "@shared/loader/loader.component";
import { LearningFieldEditorImplComponent } from '@app/components/curriculum/field/learning-field-editor-impl.component';
import { LearningFieldDetailsImplComponent } from '@app/components/curriculum/field/learning-field-details-impl.component';

@Component({
  selector: 'app-search-learning-fields',
  templateUrl: './search-learning-fields.component.html',
  styleUrls: ['./search-learning-fields.component.scss'],
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    ReactiveFormsModule,
    TranslateModule,
    MaterialModule,

    TableComponent,
    LoaderComponent,
    LearningFieldEditorImplComponent,
    LearningFieldDetailsImplComponent,
  ],
})
export class SearchLearningFieldsImplComponent extends SearchLearningFieldsComponent {

    constructor() {
        super();
    }

    override beforeOnInit(form: SearchLearningFieldsVarsForm): SearchLearningFieldsVarsForm{
        return form;
    }

    doNgOnDestroy(): void {
    }
}
