// Generated by andromda-angular cartridge (view\view.component.imp.ts.vsl) CAN EDIT!
import { Component } from '@angular/core';
import { EditModuleComponent } from '@app/view/module/edit-module.component';
import { EditModuleVarsForm } from '@app/view/module/edit-module.component';
import { MatRadioChange } from '@angular/material/radio';
import { MatCheckboxChange } from '@angular/material/checkbox';
import { CommonModule } from '@angular/common';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { TranslateModule } from '@ngx-translate/core';
import { MaterialModule } from '@app/material.module';
import { CsvModule } from '@ctrl/ngx-csv';
import { TableComponent } from '@app/components/table/table.component';
import { LoaderComponent } from "@shared/loader/loader.component";
import { ModuleDetailsImplComponent } from '@app/components/module/module-details-impl.component';
import { ModuleEditorImplComponent } from '@app/components/module/module-editor-impl.component';

@Component({
  selector: 'app-edit-module',
  templateUrl: './edit-module.component.html',
  styleUrls: ['./edit-module.component.scss'],
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    ReactiveFormsModule,
    TranslateModule,
    MaterialModule,
    CsvModule,
    TableComponent,
    LoaderComponent,
    ModuleDetailsImplComponent,
    ModuleEditorImplComponent,
  ],
})
export class EditModuleImplComponent extends EditModuleComponent {

    constructor() {
        super();
    }

    override beforeOnInit(form: EditModuleVarsForm): EditModuleVarsForm{     
        return form;
    }

    doNgOnDestroy(): void {
    }
}