// Generated by andromda-angular cartridge (view\view.component.imp.ts.vsl) CAN EDIT!
import { Component } from '@angular/core';
import { ModuleViewComponent } from '@app/view/module/module-view.component';
import { ModuleViewVarsForm } from '@app/view/module/module-view.component';
import { MatRadioChange } from '@angular/material/radio';
import { MatCheckboxChange } from '@angular/material/checkbox';
import { CommonModule } from '@angular/common';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { TranslateModule } from '@ngx-translate/core';
import { MaterialModule } from '@app/material.module';
import { CsvModule } from '@ctrl/ngx-csv';
import { TableComponent } from '@app/components/table/table.component';
import { LoaderComponent } from "@shared/loader/loader.component";
import { ModuleDetailsImplComponent } from '@app/components/module/module-details-impl.component';
import { ModuleEditorImplComponent } from '@app/components/module/module-editor-impl.component';

@Component({
  selector: 'app-module-view',
  templateUrl: './module-view.component.html',
  styleUrls: ['./module-view.component.scss'],
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    ReactiveFormsModule,
    TranslateModule,
    MaterialModule,
    CsvModule,
    TableComponent,
    LoaderComponent,
    ModuleDetailsImplComponent,
    ModuleEditorImplComponent,
  ],
})
export class ModuleViewImplComponent extends ModuleViewComponent {

    constructor() {
        super();
        this.moduleApiStore.reset();
        this.success = this.moduleApiStore.success;
        this.loading = this.moduleApiStore.loading;
        this.error = this.moduleApiStore.error;
        this.messages = this.moduleApiStore.messages;
        this.loaderMessage = this.moduleApiStore.loaderMessage;
    }

    override beforeOnInit(form: ModuleViewVarsForm): ModuleViewVarsForm{
        return form;
    }

    doNgOnDestroy(): void {
    }
}
