// Generated by hibernate/SpringHibernateDaoImpl.vsl in andromda-spring-cartridge on $springUtils.date.
// license-header java merge-point
/**
 * This is only generated once! It will never be overwritten.
 * You can (and have to!) safely modify it by hand.
 */
package bw.co.roguesystems.thutego.curriculum.year;

import org.springframework.stereotype.Repository;

import bw.co.roguesystems.thutego.curriculum.year.Year;
import bw.co.roguesystems.thutego.curriculum.year.YearDaoBase;
import bw.co.roguesystems.thutego.curriculum.year.YearRepository;
import bw.co.roguesystems.thutego.curriculum.year.YearVO;

/**
 * @see Year
 */
@Repository("yearDao")
public class YearDaoImpl
    extends YearDaoBase
{
    
    public YearDaoImpl(
        YearRepository yearRepository
    ) {

        super(
            yearRepository
        );
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public void toYearVO(
        Year source,
        YearVO target)
    {
        // TODO verify behavior of toYearVO
        super.toYearVO(source, target);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public YearVO toYearVO(final Year entity)
    {
        // TODO verify behavior of toYearVO
        return super.toYearVO(entity);
    }

    /**
     * Retrieves the entity object that is associated with the specified value object
     * from the object store. If no such entity object exists in the object store,
     * a new, blank entity is created
     */
    private Year loadYearFromYearVO(YearVO yearVO)
    {
        // TODO implement loadYearFromYearVO
        throw new UnsupportedOperationException("bw.co.roguesystems.thutego.curriculum.year.loadYearFromYearVO(YearVO) not yet implemented.");

        /* A typical implementation looks like this:
        if (yearVO.getId() == null)
        {
            return  Year.Factory.newInstance();
        }
        else
        {
            return this.load(yearVO.getId());
        }
        */
    }

    /**
     * {@inheritDoc}
     */
    public Year yearVOToEntity(YearVO yearVO)
    {
        // TODO verify behavior of yearVOToEntity
        Year entity = this.loadYearFromYearVO(yearVO);
        this.yearVOToEntity(yearVO, entity, true);
        return entity;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public void yearVOToEntity(
        YearVO source,
        Year target,
        boolean copyIfNull)
    {
        // TODO verify behavior of yearVOToEntity
        super.yearVOToEntity(source, target, copyIfNull);
    }
}