// Generated by andromda-angular cartridge (view\view.component.imp.ts.vsl) CAN EDIT!
import { Component } from '@angular/core';
import { EditAccessPointComponent } from '@app/view/access/edit-access-point.component';
import { EditAccessPointVarsForm } from '@app/view/access/edit-access-point.component';
import { MatRadioChange } from '@angular/material/radio';
import { MatCheckboxChange } from '@angular/material/checkbox';
import { CommonModule } from '@angular/common';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { TranslateModule } from '@ngx-translate/core';
import { MaterialModule } from '@app/material.module';
import { CsvModule } from '@ctrl/ngx-csv';
import { TableComponent } from '@app/components/table/table.component';
import { LoaderComponent } from "@shared/loader/loader.component";
import { AccessPointEditorImplComponent } from '@app/components/access/access-point-editor-impl.component';

@Component({
  selector: 'app-edit-access-point',
  templateUrl: './edit-access-point.component.html',
  styleUrls: ['./edit-access-point.component.scss'],
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    ReactiveFormsModule,
    TranslateModule,
    MaterialModule,
    CsvModule,
    TableComponent,
    LoaderComponent,
    AccessPointEditorImplComponent,
  ],
})
export class EditAccessPointImplComponent extends EditAccessPointComponent {

  constructor() {
    super();
    this.accessPointApiStore.reset();
    this.success = this.accessPointApiStore.success;
    this.loading = this.accessPointApiStore.loading;
    this.error = this.accessPointApiStore.error;
    this.messages = this.accessPointApiStore.messages;
  }

  override beforeOnInit(form: EditAccessPointVarsForm): EditAccessPointVarsForm {
    this.route.queryParams.subscribe((params: any) => {
      if (params.id) {
        this.accessPointApiStore.findById(params);
      }
    });
    return form;
  }

  doNgOnDestroy(): void {
  }

  override beforeEditAccessPointSave(form: any): void {
    let accessPoint = this.accessPoint.formGroupControl.value;
    this.accessPointApiStore.save({ accessPoint });
  }
}
