// Generated by andromda-angular cartridge (view\view.component.imp.ts.vsl) CAN EDIT!
import { Component } from '@angular/core';
import { SearchAccessPointsComponent } from '@app/view/access/search-access-points.component';
import { SearchAccessPointsVarsForm } from '@app/view/access/search-access-points.component';
import { MatRadioChange } from '@angular/material/radio';
import { MatCheckboxChange } from '@angular/material/checkbox';
import { CommonModule } from '@angular/common';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { TranslateModule } from '@ngx-translate/core';
import { MaterialModule } from '@app/material.module';
import { CsvModule } from '@ctrl/ngx-csv';
import { TableComponent } from '@app/components/table/table.component';
import { LoaderComponent } from "../../@shared/loader/loader.component";
import { AccessPointSearchImplComponent } from '@app/components/access/access-point-search-impl.component';

@Component({
  selector: 'app-search-access-points',
  templateUrl: './search-access-points.component.html',
  styleUrls: ['./search-access-points.component.scss'],
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    ReactiveFormsModule,
    TranslateModule,
    MaterialModule,
    CsvModule,
    TableComponent,
    LoaderComponent,
    AccessPointSearchImplComponent,
  ],
})
export class SearchAccessPointsImplComponent extends SearchAccessPointsComponent {

    constructor() {
        super();
    }

    override beforeOnInit(form: SearchAccessPointsVarsForm): SearchAccessPointsVarsForm{     
        return form;
    }

    doNgOnDestroy(): void {
    }
}