// Generated by andromda-angular cartridge (view\view.component.imp.ts.vsl) CAN EDIT!
import { Component } from '@angular/core';
import { EditDomainComponent } from '@app/view/curriculum/domain/edit-domain.component';
import { EditDomainVarsForm } from '@app/view/curriculum/domain/edit-domain.component';
import { MatRadioChange } from '@angular/material/radio';
import { MatCheckboxChange } from '@angular/material/checkbox';
import { CommonModule } from '@angular/common';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { TranslateModule } from '@ngx-translate/core';
import { SharedModule } from '@app/@shared';
import { MaterialModule } from '@app/material.module';
import { CsvModule } from '@ctrl/ngx-csv';
import { TableComponent } from '@app/components/table/table.component';
import { DomainEditorImplComponent } from '@app/components/curriculum/domain/domain-editor-impl.component';
import { DomainDetailsImplComponent } from '@app/components/curriculum/domain/domain-details-impl.component';

@Component({
  selector: 'app-edit-domain',
  templateUrl: './edit-domain.component.html',
  styleUrls: ['./edit-domain.component.scss'],
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    ReactiveFormsModule,
    TranslateModule,
    SharedModule,
    MaterialModule,
    CsvModule,
    TableComponent,
    DomainEditorImplComponent,
    DomainDetailsImplComponent,
  ],
})
export class EditDomainImplComponent extends EditDomainComponent {

  constructor() {
    super();
    this.domainApiStore.reset()
    this.success = this.domainApiStore.success;
    this.loading = this.domainApiStore.loading;
    this.error = this.domainApiStore.error;
    this.messages = this.domainApiStore.messages;
  }

  override beforeOnInit(form: EditDomainVarsForm): EditDomainVarsForm {
    return form;
  }

  doNgOnDestroy(): void {
  }

  override beforeEditDomainSave(form: any): void {

    form.domain = { ...this.domainEditorComponent?.domainEditorForm?.value };
    this.domainApiStore.save(form);
  }
}
