// Generated by andromda-angular cartridge (view\view.component.imp.ts.vsl) CAN EDIT!
import { Component } from '@angular/core';
import { EditDomainComponent } from '@app/view/curriculum/domain/edit-domain.component';
import { EditDomainVarsForm } from '@app/view/curriculum/domain/edit-domain.component';
import { MatRadioChange } from '@angular/material/radio';
import { MatCheckboxChange } from '@angular/material/checkbox';
import { CommonModule } from '@angular/common';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { TranslateModule } from '@ngx-translate/core';
import { MaterialModule } from '@app/material.module';

import { TableComponent } from '@app/components/table/table.component';
import { LoaderComponent } from "@shared/loader/loader.component";
import { DomainDetailsImplComponent } from '@app/components/curriculum/domain/domain-details-impl.component';
import { DomainEditorImplComponent } from '@app/components/curriculum/domain/domain-editor-impl.component';

@Component({
  selector: 'app-edit-domain',
  templateUrl: './edit-domain.component.html',
  styleUrls: ['./edit-domain.component.scss'],
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    ReactiveFormsModule,
    TranslateModule,
    MaterialModule,

    TableComponent,
    LoaderComponent,
    DomainDetailsImplComponent,
    DomainEditorImplComponent,
  ],
})
export class EditDomainImplComponent extends EditDomainComponent {

    constructor() {
        super();
    }

    override beforeOnInit(form: EditDomainVarsForm): EditDomainVarsForm{
        return form;
    }

    doNgOnDestroy(): void {
    }
}
