// Generated by andromda-angular cartridge (view\view.component.imp.ts.vsl) CAN EDIT!
import { Component } from '@angular/core';
import { SearchDomainsComponent } from '@app/view/curriculum/domain/search-domains.component';
import { SearchDomainsVarsForm } from '@app/view/curriculum/domain/search-domains.component';
import { MatRadioChange } from '@angular/material/radio';
import { MatCheckboxChange } from '@angular/material/checkbox';
import { CommonModule } from '@angular/common';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { TranslateModule } from '@ngx-translate/core';
import { MaterialModule } from '@app/material.module';

import { TableComponent } from '@app/components/table/table.component';
import { LoaderComponent } from "@shared/loader/loader.component";
import { DomainEditorImplComponent } from '@app/components/curriculum/domain/domain-editor-impl.component';

@Component({
  selector: 'app-search-domains',
  templateUrl: './search-domains.component.html',
  styleUrls: ['./search-domains.component.scss'],
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    ReactiveFormsModule,
    TranslateModule,
    MaterialModule,

    TableComponent,
    LoaderComponent,
    DomainEditorImplComponent,
  ],
})
export class SearchDomainsImplComponent extends SearchDomainsComponent {

    constructor() {
        super();
    }

    override beforeOnInit(form: SearchDomainsVarsForm): SearchDomainsVarsForm{
        return form;
    }

    doNgOnDestroy(): void {
    }
}
