// Generated by andromda-angular cartridge (view\view.component.imp.ts.vsl) CAN EDIT!
import { Component } from '@angular/core';
import { EditInstitutionComponent } from '@app/view/institution/edit-institution.component';
import { EditInstitutionVarsForm } from '@app/view/institution/edit-institution.component';
import { MatRadioChange } from '@angular/material/radio';
import { MatCheckboxChange } from '@angular/material/checkbox';
import { CommonModule } from '@angular/common';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { TranslateModule } from '@ngx-translate/core';
import { MaterialModule } from '@app/material.module';
import { CsvModule } from '@ctrl/ngx-csv';
import { TableComponent } from '@app/components/table/table.component';
import { LoaderComponent } from "@shared/loader/loader.component";
import { InstitutionDetailsImplComponent } from '@app/components/institution/institution-details-impl.component';
import { InstitutionEditorImplComponent } from '@app/components/institution/institution-editor-impl.component';

@Component({
  selector: 'app-edit-institution',
  templateUrl: './edit-institution.component.html',
  styleUrls: ['./edit-institution.component.scss'],
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    ReactiveFormsModule,
    TranslateModule,
    MaterialModule,
    CsvModule,
    TableComponent,
    LoaderComponent,
    InstitutionDetailsImplComponent,
    InstitutionEditorImplComponent,
  ],
})
export class EditInstitutionImplComponent extends EditInstitutionComponent {

    constructor() {
        super();
    }

    override beforeOnInit(form: EditInstitutionVarsForm): EditInstitutionVarsForm{     
        return form;
    }

    doNgOnDestroy(): void {
    }
}