// Generated by andromda-angular cartridge (view\view.component.imp.ts.vsl) CAN EDIT!
import { Component } from '@angular/core';
import { EditInstitutionComponent } from '@app/view/institution/edit-institution.component';
import { EditInstitutionVarsForm } from '@app/view/institution/edit-institution.component';
import { MatRadioChange } from '@angular/material/radio';
import { MatCheckboxChange } from '@angular/material/checkbox';
import { CommonModule } from '@angular/common';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { TranslateModule } from '@ngx-translate/core';
import { SharedModule } from '@app/@shared';
import { MaterialModule } from '@app/material.module';
import { CsvModule } from '@ctrl/ngx-csv';
import { TableComponent } from '@app/components/table/table.component';
import { InstitutionEditorImplComponent } from '@app/components/institution/institution-editor-impl.component';
import { InstitutionDetailsImplComponent } from '@app/components/institution/institution-details-impl.component';

@Component({
  selector: 'app-edit-institution',
  templateUrl: './edit-institution.component.html',
  styleUrls: ['./edit-institution.component.scss'],
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    ReactiveFormsModule,
    TranslateModule,
    SharedModule,
    MaterialModule,
    CsvModule,
    TableComponent,
    InstitutionEditorImplComponent,
    InstitutionDetailsImplComponent,
  ],
})
export class EditInstitutionImplComponent extends EditInstitutionComponent {

  constructor() {
    super();
    this.success = this.institutionApiStore.success;
    this.loading = this.institutionApiStore.loading;
    this.error = this.institutionApiStore.error;
    this.messages = this.institutionApiStore.messages;
  }

  override beforeOnInit(form: EditInstitutionVarsForm): EditInstitutionVarsForm {
    return form;
  }

  doNgOnDestroy(): void {
  }

  override beforeEditInstitutionSave(form: any): void {

    form.institution = { ...this.institutionEditor?.institutionEditorForm?.value };
    this.institutionApiStore.save(form);

  }
}
