// Generated by andromda-angular cartridge (view\view.component.imp.ts.vsl) CAN EDIT!
import { Component } from '@angular/core';
import { InstitutionViewComponent } from '@app/view/institution/institution-view.component';
import { InstitutionViewVarsForm } from '@app/view/institution/institution-view.component';
import { MatRadioChange } from '@angular/material/radio';
import { MatCheckboxChange } from '@angular/material/checkbox';
import { CommonModule } from '@angular/common';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { TranslateModule } from '@ngx-translate/core';
import { SharedModule } from '@app/@shared';
import { MaterialModule } from '@app/material.module';
import { CsvModule } from '@ctrl/ngx-csv';
import { TableComponent } from '@app/components/table/table.component';
import { InstitutionEditorComponent } from '@app/components/institution/institution-editor.component';
import { InstitutionDetailsComponent } from '@app/components/institution/institution-details.component';

@Component({
  selector: 'app-institution-view',
  templateUrl: './institution-view.component.html',
  styleUrls: ['./institution-view.component.scss'],
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    ReactiveFormsModule,
    TranslateModule,
    SharedModule,
    MaterialModule,
    CsvModule,
    TableComponent,
    InstitutionEditorComponent,
    InstitutionDetailsComponent,
  ],
})
export class InstitutionViewImplComponent extends InstitutionViewComponent {

    constructor() {
        super();
        this.success = this.institutionApiStore.success;
        this.loading = this.institutionApiStore.loading;
        this.error = this.institutionApiStore.error;
        this.messages = this.institutionApiStore.messages;
    }

    override beforeOnInit(form: InstitutionViewVarsForm): InstitutionViewVarsForm{
        return form;
    }

    doNgOnDestroy(): void {
    }
}
