// Generated by andromda-angular cartridge (view\view.component.imp.ts.vsl) CAN EDIT!
import { Component, inject } from '@angular/core';
import { SearchInstitutionsComponent } from '@app/view/institution/search-institutions.component';
import { SearchInstitutionsVarsForm } from '@app/view/institution/search-institutions.component';
import { MatRadioChange } from '@angular/material/radio';
import { MatCheckboxChange } from '@angular/material/checkbox';
import { CommonModule } from '@angular/common';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { TranslateModule } from '@ngx-translate/core';
import { SharedModule } from '@app/@shared';
import { MaterialModule } from '@app/material.module';
import { CsvModule } from '@ctrl/ngx-csv';
import { TableComponent } from '@app/components/table/table.component';
import { InstitutionEditorComponent } from '@app/components/institution/institution-editor.component';
import { InstitutionDetailsComponent } from '@app/components/institution/institution-details.component';
import { InstitutionApiStore } from '@app/store/bw/co/roguesystems/thutego/institution/institution-api.store';

@Component({
  selector: 'app-search-institutions',
  templateUrl: './search-institutions.component.html',
  styleUrls: ['./search-institutions.component.scss'],
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    ReactiveFormsModule,
    TranslateModule,
    SharedModule,
    MaterialModule,
    CsvModule,
    TableComponent,
    InstitutionEditorComponent,
    InstitutionDetailsComponent,
  ],
})
export class SearchInstitutionsImplComponent extends SearchInstitutionsComponent {

    constructor() {
        super();
        this.success = this.institutionApiStore.success;
        this.loading = this.institutionApiStore.loading;
        this.error = this.institutionApiStore.error;
        this.messages = this.institutionApiStore.messages;

    }

    override beforeOnInit(form: SearchInstitutionsVarsForm): SearchInstitutionsVarsForm{
        return form;
    }

    doNgOnDestroy(): void {
    }

    override beforeSearchInstitutionsSearch(form: any): void {
      console.log('beforeSearchInstitutionsSearch');
    }
}
