// Generated by andromda-jsf cartridge (view\table\table-impl.component.ts.vsl)
import { Component } from '@angular/core';
import { SearchInstitutionsInstitutionsComponent } from '@app/view/institution/search-institutions-institutions.component';
import { CommonModule } from '@angular/common';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { TranslateModule } from '@ngx-translate/core';
import { SharedModule } from '@app/@shared';
import { MaterialModule } from '@app/material.module';
import { CsvModule } from '@ctrl/ngx-csv';

@Component({
  selector: 'app-search-institutions-institutions',
  templateUrl: './search-institutions-institutions.component.html',
  styleUrls: [ './search-institutions-institutions.component.scss' ],
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    ReactiveFormsModule,
    TranslateModule,
    SharedModule,
    MaterialModule,
    CsvModule,
  ],
})
export class SearchInstitutionsInstitutionsImplComponent extends SearchInstitutionsInstitutionsComponent {

  constructor() {
    super();
  }


	override doSearchInstitutionsEdit(form: any): any {
    return form;
	}
}