// Generated by andromda-angular cartridge (controller\controller.impl.ts.vsl) Can Modify
import { Injectable } from '@angular/core';
import { DomainController } from '@app/controller/curriculum/domain/domain-controller';

@Injectable()
export class DomainControllerImpl extends DomainController {

    constructor() {
        super();
    }

}
