// Generated by andromda-angular cartridge (service\service.impl.ts.vsl) CAN EDIT
import { Injectable, inject } from '@angular/core';
import { Observable } from 'rxjs';
import { DomainVO } from '@app/model/bw/co/roguesystems/thutego/curriculum/domain/domain-vo';
import { HttpClient } from '@angular/common/http';
import { Page } from '@app/model/page.model';
import { SearchObject } from '@app/model/search-object';

@Injectable({
  providedIn: 'root'
})
export class DomainApi {
    
    protected path = '/curriculum/domain';

    private http = inject(HttpClient);

    public findById(id: number | any ): Observable<DomainVO | any> {

        return this.http.get<DomainVO | any>(this.path + `/${id}`);
    }

    public getAll(): Observable<DomainVO[] | any[]> {

        return this.http.get<DomainVO[] | any[]>(this.path);
    }

    public remove(id: number | any ): Observable<boolean | any> {

        return this.http.delete<boolean | any>(this.path + `/${id}`);
    }

    public save(domain: DomainVO | any ): Observable<DomainVO | any> {

        return this.http.post<DomainVO | any>(this.path, domain);
    }

    public search(criteria: string | any ): Observable<DomainVO[] | any[]> {

        return this.http.get<DomainVO[] | any[]>(this.path + `/search?criteria=${criteria}`);
    }

}
