// Generated by hibernate/SpringHibernateDaoImpl.vsl in andromda-spring-cartridge on $springUtils.date.
// license-header java merge-point
/**
 * This is only generated once! It will never be overwritten.
 * You can (and have to!) safely modify it by hand.
 */
package bw.co.roguesystems.thutego.curricullum.level;

import bw.co.roguesystems.thutego.curricullum.CurricullumRepository;
import org.springframework.stereotype.Repository;

/**
 * @see CurriculumLevel
 */
@Repository("curriculumLevelDao")
public class CurriculumLevelDaoImpl
    extends CurriculumLevelDaoBase
{
    
    public CurriculumLevelDaoImpl(
        CurricullumRepository curricullumRepository,
        CurriculumLevelRepository curriculumLevelRepository
    ) {

        super(
            curricullumRepository,
            curriculumLevelRepository
        );
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public void toCurriculumLevelVO(
        CurriculumLevel source,
        CurriculumLevelVO target)
    {
        // TODO verify behavior of toCurriculumLevelVO
        super.toCurriculumLevelVO(source, target);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CurriculumLevelVO toCurriculumLevelVO(final CurriculumLevel entity)
    {
        // TODO verify behavior of toCurriculumLevelVO
        return super.toCurriculumLevelVO(entity);
    }

    /**
     * Retrieves the entity object that is associated with the specified value object
     * from the object store. If no such entity object exists in the object store,
     * a new, blank entity is created
     */
    private CurriculumLevel loadCurriculumLevelFromCurriculumLevelVO(CurriculumLevelVO curriculumLevelVO)
    {
        if (curriculumLevelVO.getId() == null)
        {
            return  CurriculumLevel.Factory.newInstance();
        }
        else
        {
            return this.load(curriculumLevelVO.getId());
        }
    }

    /**
     * {@inheritDoc}
     */
    public CurriculumLevel curriculumLevelVOToEntity(CurriculumLevelVO curriculumLevelVO)
    {
        // TODO verify behavior of curriculumLevelVOToEntity
        CurriculumLevel entity = this.loadCurriculumLevelFromCurriculumLevelVO(curriculumLevelVO);
        this.curriculumLevelVOToEntity(curriculumLevelVO, entity, true);
        return entity;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public void curriculumLevelVOToEntity(
        CurriculumLevelVO source,
        CurriculumLevel target,
        boolean copyIfNull)
    {
        // TODO verify behavior of curriculumLevelVOToEntity
        super.curriculumLevelVOToEntity(source, target, copyIfNull);
    }
}