// Generated by andromda-angular cartridge (controller\controller.impl.ts.vsl) Can Modify
import { Injectable } from '@angular/core';
import { ExitLevelOutcomeController } from '@app/controller/curriculum/outcome/exit-level-outcome-controller';

@Injectable()
export class ExitLevelOutcomeControllerImpl extends ExitLevelOutcomeController {

    constructor() {
        super();
    }

}
