// Generated by andromda-angular cartridge (controller\controller.impl.ts.vsl) Can Modify
import { Injectable } from '@angular/core';
import { InstitutionController } from '@app/controller/institution/institution-controller';

@Injectable()
export class InstitutionControllerImpl extends InstitutionController {

    constructor() {
        super();
    }

}
