// Generated by andromda-angular cartridge (view\view.component.imp.ts.vsl) CAN EDIT!
import { Component } from '@angular/core';
import { EditAccessPointTypeComponent } from '@app/view/access/type/edit-access-point-type.component';
import { EditAccessPointTypeVarsForm } from '@app/view/access/type/edit-access-point-type.component';
import { MatRadioChange } from '@angular/material/radio';
import { MatCheckboxChange } from '@angular/material/checkbox';
import { CommonModule } from '@angular/common';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { TranslateModule } from '@ngx-translate/core';
import { MaterialModule } from '@app/material.module';
import { CsvModule } from '@ctrl/ngx-csv';
import { TableComponent } from '@app/components/table/table.component';
import { LoaderComponent } from "@shared/loader/loader.component";

@Component({
  selector: 'app-edit-access-point-type',
  templateUrl: './edit-access-point-type.component.html',
  styleUrls: ['./edit-access-point-type.component.scss'],
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    ReactiveFormsModule,
    TranslateModule,
    MaterialModule,
    CsvModule,
    TableComponent,
    LoaderComponent,
  ],
})
export class EditAccessPointTypeImplComponent extends EditAccessPointTypeComponent {

    constructor() {
        super();
    }

    override beforeOnInit(form: EditAccessPointTypeVarsForm): EditAccessPointTypeVarsForm{     
        return form;
    }

    doNgOnDestroy(): void {
    }
}