// Generated by andromda-angular cartridge (view\view.component.imp.ts.vsl) CAN EDIT!
import { Component } from '@angular/core';
import { SearchUsersComponent } from '@app/view/user/search-users.component';
import { SearchUsersVarsForm } from '@app/view/user/search-users.component';
import { MatRadioChange } from '@angular/material/radio';
import { MatCheckboxChange } from '@angular/material/checkbox';
import { CommonModule } from '@angular/common';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { TranslateModule } from '@ngx-translate/core';
import { MaterialModule } from '@app/material.module';
import { CsvModule } from '@ctrl/ngx-csv';
import { TableComponent } from '@app/components/table/table.component';
import { LoaderComponent } from "@shared/loader/loader.component";

@Component({
  selector: 'app-search-users',
  templateUrl: './search-users.component.html',
  styleUrls: ['./search-users.component.scss'],
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    ReactiveFormsModule,
    TranslateModule,
    MaterialModule,
    CsvModule,
    TableComponent,
    LoaderComponent,
  ],
})
export class SearchUsersImplComponent extends SearchUsersComponent {

    constructor() {
        super();
        this.userApiStore.reset();
        this.success = this.userApiStore.success;
        this.loading = this.userApiStore.loading;
        this.error = this.userApiStore.error;
        this.messages = this.userApiStore.messages;
        this.loaderMessage = this.userApiStore.loaderMessage;
        this.usersTablePaged = true;
        this.usersTableSignal = this.userApiStore.dataPage;
    }

    override beforeOnInit(form: SearchUsersVarsForm): SearchUsersVarsForm{
        return form;
    }

    doNgOnDestroy(): void {
    }
}
