// Generated by andromda-angular cartridge (service\service.impl.ts.vsl) CAN EDIT
import { Injectable, inject } from '@angular/core';
import { Observable } from 'rxjs';
import { OrganisationVO } from '@app/model/bw/co/roguesystems/thutego/organisation/organisation-vo';
import { HttpClient } from '@angular/common/http';
import { Page } from '@app/model/page.model';
import { SearchObject } from '@app/model/search-object';

@Injectable({
  providedIn: 'root'
})
export class OrganisationApi {
    
    protected path = '/organisation';

    private http = inject(HttpClient);

    public findById(id: number | any ): Observable<OrganisationVO | any> {

        return this.http.get<OrganisationVO | any>(this.path + `/${id}`);
    }

    public getAll(): Observable<OrganisationVO[] | any[]> {

        return this.http.get<OrganisationVO[] | any[]>(this.path);
    }

    public remove(id: number | any ): Observable<boolean | any> {

        return this.http.delete<boolean | any>(this.path + `/${id}`);
    }

    public save(organisation: OrganisationVO | any ): Observable<OrganisationVO | any> {

        return this.http.post<OrganisationVO | any>(this.path, organisation);
    }

    public search(criteria: string | any ): Observable<OrganisationVO[] | any[]> {

        return this.http.get<OrganisationVO[] | any[]>(this.path + `/search?criteria=${criteria}`);
    }

}
