// Generated by andromda-angular cartridge (controller\controller.impl.ts.vsl) Can Modify
import { Injectable } from '@angular/core';
import { ProgrammeController } from '@app/controller/programme/programme-controller';

@Injectable()
export class ProgrammeControllerImpl extends ProgrammeController {

    constructor() {
        super();
    }

}
