// Generated by andromda-angular cartridge (service\service.impl.ts.vsl) CAN EDIT
import { Injectable, inject } from '@angular/core';
import { Observable } from 'rxjs';
import { LearningFieldVO } from '@app/model/bw/co/roguesystems/thutego/curricullum/field/learning-field-vo';
import { HttpClient } from '@angular/common/http';
import { Page } from '@app/model/page.model';
import { SearchObject } from '@app/model/search-object';

@Injectable({
  providedIn: 'root'
})
export class LearningFieldApi {
    
    protected path = '/curriculum/field';

    private http = inject(HttpClient);

    public findById(id: number | any ): Observable<LearningFieldVO | any> {


        return this.http.get<LearningFieldVO | any>(this.path + `/${id}`);

    }

    public getAll(): Observable<LearningFieldVO[] | any[]> {


        return this.http.get<LearningFieldVO[] | any[]>(this.path);

    }

    public remove(id: number | any ): Observable<boolean | any> {


        return this.http.delete<boolean | any>(this.path + `/${id}`);

    }

    public save(field: LearningFieldVO | any ): Observable<LearningFieldVO | any> {


        return this.http.post<LearningFieldVO | any>(this.path, field);

    }

    public search(criteria: string | any ): Observable<LearningFieldVO[] | any[]> {


        return this.http.get<LearningFieldVO[] | any[]>(this.path + `/search?criteria=${criteria}`);

    }

}
