// Generated by andromda-angular cartridge (service\service.impl.ts.vsl) CAN EDIT
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { ExitLevelOutcomeVO } from '@app/model/bw/co/roguesystems/thutego/curricullum/outcome/exit-level-outcome-vo';
import { HttpClient } from '@angular/common/http';
import { Page } from '@app/model/page.model';
import { SearchObject } from '@app/model/search-object';

@Injectable({
  providedIn: 'root'
})
export class ExitLevelOutcomeController {
    
    protected path = '/curriculum/outcome';

    constructor(private http: HttpClient) {
    }

    public findById(id: number | any ): Observable<ExitLevelOutcomeVO | any> {

        return this.http.get<ExitLevelOutcomeVO | any>(this.path + `/${id}`);

    }

    public getAll(): Observable<ExitLevelOutcomeVO[] | any[]> {

        return this.http.get<ExitLevelOutcomeVO[] | any[]>(this.path);

    }

    public remove(id: number | any ): Observable<boolean | any> {

        return this.http.delete<boolean | any>(this.path + `/${id}`);

    }

    public save(exitLevelOutcome: ExitLevelOutcomeVO | any ): Observable<ExitLevelOutcomeVO | any> {

        return this.http.post<ExitLevelOutcomeVO | any>(this.path, exitLevelOutcome);

    }

    public search(criteria: string | any ): Observable<ExitLevelOutcomeVO[] | any[]> {

        return this.http.get<ExitLevelOutcomeVO[] | any[]>(this.path + `/search`);

    }

}
