// Generated by andromda-angular cartridge (controller\controller.impl.ts.vsl) Can Modify
import { Injectable } from '@angular/core';
import { CurriculumLevelController } from '@app/controller/curriculum/level/curriculum-level-controller';

@Injectable()
export class CurriculumLevelControllerImpl extends CurriculumLevelController {

    constructor() {
        super();
    }

}
