// Generated by andromda-angular cartridge (controller\controller.impl.ts.vsl) Can Modify
import { Injectable } from '@angular/core';
import { ModuleController } from '@app/controller/module/module-controller';

@Injectable()
export class ModuleControllerImpl extends ModuleController {

    constructor() {
        super();
    }

}
