// Generated by andromda-angular cartridge (service\service.impl.ts.vsl) CAN EDIT
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { YearVO } from '@app/model/bw/co/roguesystems/thutego/curricullum/year/year-vo';
import { HttpClient } from '@angular/common/http';
import { Page } from '@app/model/page.model';
import { SearchObject } from '@app/model/search-object';

@Injectable({
  providedIn: 'root'
})
export class YearApi {
    
    protected path = '/year';

    constructor(private http: HttpClient) {
    }

    public findById(id: number | any ): Observable<YearVO | any> {

        return this.http.get<YearVO | any>(this.path + `/${id}`);

    }

    public getAll(): Observable<YearVO[] | any[]> {

        return this.http.get<YearVO[] | any[]>(this.path);

    }

    public remove(id: number | any ): Observable<boolean | any> {

        return this.http.delete<boolean | any>(this.path + `/${id}`);

    }

    public save(curriculumLevel: YearVO | any ): Observable<YearVO | any> {

        return this.http.post<YearVO | any>(this.path, curriculumLevel);

    }

    public search(criteria: string | any ): Observable<YearVO[] | any[]> {

        return this.http.get<YearVO[] | any[]>(this.path + `/search`);

    }

}
